spring:
  application:
    name: JPA_HIBERNATE_2_HOMEWORK
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_hibernate_2_homework
    username: postgres
    password: 2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    org.example.jpa2: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE